---
# tasks file for nginx
- name: Install nginx.
  yum: name=nginx

- name: copy index.html
  template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

- command: chkconfig nginx on
- command: service nginx restart
